package com.yss.scala.dto

case class SJSJGETL(
                     JGJSZH: String,
                     JGBFZH: String,
                     JGSJLX: String,
                     JGYWLB: String,
                     JGZQDM: String,
                     JGJYDY: String,
                     JGTGDY: String,
                     JGZQZH: String,
                     JGDDBH: String,
                     JGYYB: String,
                     JGZXBH: String,
                     JGYWLSH: String,
                     JGCJSL: String,
                     JGQSSL: String,
                     JGJSSL: String,
                     JGCJJG: String,
                     JGQSJG: String,
                     JGXYJY: String,
                     JGPCBS: String,
                     JGZQLB: String,
                     JGZQZL: String,
                     JGGFXZ: String,
                     JGLTLX: String,
                     JGJSFS: String,
                     JGHBDH: String,
                     JGQSBJ: String,
                     JGYHS: String,
                     JGJYJSF: String,
                     JGJGGF: String,
                     JGGHF: String,
                     JGJSF: String,
                     JGSXF: String,
                     JGQSYJ: String,
                     JGQTFY: String,
                     JGZJJE: String,
                     JGSFJE: String,
                     JGJSBZ: String,
                     JGZYDH: String,
                     JGCJRQ: String,
                     JGQSRQ: String,
                     JGJSRQ: String,
                     JGFSRQ: String,
                     JGQTRQ: String,
                     JGSCDM: String,
                     JGJYFS: String,
                     JGZQDM2: String,
                     JGTGDY2: String,
                     JGDDBH2: String,
                     JGFJSM: String,
                     JGBYBZ: String
                   )

case class SJSJGETL_PT(
                     JGJSZH: String,
                     JGBFZH: String,
                     JGSJLX: String,
                     JGYWLB: String,
                     JGZQDM: String,
                     JGJYDY: String,
                     JGTGDY: String,
                     JGZQZH: String,
                     JGDDBH: String,
                     JGYYB: String,
                     JGZXBH: String,
                     JGYWLSH: String,
                     JGCJSL: String,
                     JGQSSL: String,
                     JGJSSL: String,
                     JGCJJG: String,
                     JGQSJG: String,
                     JGXYJY: String,
                     JGPCBS: String,
                     JGZQLB: String,
                     JGZQZL: String,
                     JGGFXZ: String,
                     JGLTLX: String,
                     JGJSFS: String,
                     JGHBDH: String,
                     JGQSBJ: String,
                     JGYHS: String,
                     JGJYJSF: String,
                     JGJGGF: String,
                     JGGHF: String,
                     JGJSF: String,
                     JGSXF: String,
                     JGQSYJ: String,
                     JGQTFY: String,
                     JGZJJE: String,
                     JGSFJE: String,
                     JGJSBZ: String,
                     JGZYDH: String,
                     JGCJRQ: String,
                     JGQSRQ: String,
                     JGJSRQ: String,
                     JGFSRQ: String,
                     JGQTRQ: String,
                     JGSCDM: String,
                     JGJYFS: String,
                     JGZQDM2: String,
                     JGTGDY2: String,
                     JGDDBH2: String,
                     JGFJSM: String,
                     JGBYBZ: String,
                     FZQBZ: String,
                     FYWBZ: String,
                     TZH:String,
                     FGZLX:String,
                     FSETID:String

                   )

case class SjsjgFeeSum(
                     CTYPE: String,
                     CJJE: BigDecimal,
                     CJSL: BigDecimal,
                     YJ: BigDecimal,
                     JSF: BigDecimal,
                     YHS: BigDecimal,
                     ZGF: BigDecimal,
                     GHF: BigDecimal,
                     FXJ: BigDecimal,
                     GZLX:BigDecimal,
                     HGSY:BigDecimal,
                     HGTS:String)
